---
abstract: 'Graphical User Interface Design From A Text Editor'
author:
  - 'Saif Ahmed <saiftynet { at } gmail.com>'
build_requires:
  Test::More: 1.001014
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GUIDeFATE
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.13
